<?php
declare(strict_types=1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Save the selected language in the session.
if (isset($_GET["lang"]) && in_array($_GET["lang"], ["en", "it"], true)) {
    $_SESSION["lang"] = $_GET["lang"];
}

$lang = $_SESSION["lang"] ?? "en";

$translations = [
    "en" => [
        "shop" => "Shop",
        "cart" => "Cart",
        "my_orders" => "My Orders",
        "wishlist" => "Wishlist",
        "login" => "Login",
        "register" => "Register",
        "logout" => "Logout",
        "admin" => "Admin",
        "hi" => "Hi",
        "checkout" => "Checkout",
        "add_to_cart" => "Add to Cart",
        "out_of_stock" => "Out of Stock",
        "stock" => "Stock",
        "price" => "Price",
        "quantity" => "Qty",
        "total" => "Total",
        "subtotal" => "Subtotal",
        "product" => "Product",
        "sum" => "Sum",
        "continue_shopping" => "Continue Shopping",
        "start_shopping" => "Start Shopping",
        "proceed_to_checkout" => "Proceed to Checkout",
        "shopping_cart" => "Shopping Cart",
        "review_items" => "Review your items",
        "cart_empty" => "Your cart is empty.",
        "total_amount" => "Total Amount",
        "demo_checkout_note" => "By clicking Checkout, you agree that this is a demo.",
        "stock_issues" => "Stock Availability Issues",
        "stock_changed" => "Stock Availability Changed",
        "stock_too_low" => "Stock too low",
        "only_available" => "Only",
        "available" => "Available",
        "requested" => "Requested",
        "in_cart" => "in cart",
        "back_to_cart" => "Back to Cart",
        "secure_checkpoint" => "Secure Checkpoint",
        "shipping_details" => "Shipping Details",
        "payment_details" => "Payment Details",
        "first_name" => "First Name",
        "last_name" => "Last Name",
        "address" => "Address",
        "city" => "City",
        "zip_code" => "Zip Code",
        "country" => "Country",
        "card_number" => "Card Number",
        "expiry" => "Expiry",
        "pay" => "Pay",
        "demo_payment" => "Demo payment - no card validation",
        "order_summary" => "Order Summary",
        "currency" => "Currency",
        "promo_code" => "Enter Promo Code",
        "apply" => "Apply",
        "discount" => "Discount",
        "order_success" => "Order placed successfully",
        "delivery" => "Delivery in 2-3 working days",
        "view_invoice" => "View Invoice",
        "invoice" => "Invoice",
        "invoice_details" => "Invoice Details",
        "print_invoice" => "Print Invoice",
        "thank_purchase" => "Thank you for your purchase",
        "customer" => "Customer",
        "date" => "Date",
        "view_details" => "View Details",
        "order_history" => "Your TechTrade order history",
        "no_orders" => "You have no orders yet.",
        "order" => "Order",
        "item_total" => "Item Total",
        "order_id" => "Order ID",
        "order_date" => "Order Date",
        "catalog" => "Catalog",
        "filter_by" => "Filter by",
        "go" => "Go",
        "view_all" => "View All",
        "no_products" => "No products found in this category.",
        "my_wishlist" => "My Wishlist",
        "wishlist_subtitle" => "Your curated collection",
        "wishlist_empty" => "Your wishlist is empty.",
        "explore_products" => "Explore Products",
        "login_to_buy" => "Login to Buy",
        "remove_wishlist" => "Remove from wishlist",
        "add_wishlist" => "Add to wishlist",
        "footer_text" => "Built for premium tech enthusiasts.",
    ],
    "it" => [
        "shop" => "Negozio",
        "cart" => "Carrello",
        "my_orders" => "I miei ordini",
        "wishlist" => "Preferiti",
        "login" => "Accedi",
        "register" => "Registrati",
        "logout" => "Esci",
        "admin" => "Admin",
        "hi" => "Ciao",
        "checkout" => "Pagamento",
        "add_to_cart" => "Aggiungi al carrello",
        "out_of_stock" => "Esaurito",
        "stock" => "Disponibilita",
        "price" => "Prezzo",
        "quantity" => "Qta",
        "total" => "Totale",
        "subtotal" => "Subtotale",
        "product" => "Prodotto",
        "sum" => "Somma",
        "continue_shopping" => "Continua gli acquisti",
        "start_shopping" => "Inizia gli acquisti",
        "proceed_to_checkout" => "Vai al pagamento",
        "shopping_cart" => "Carrello",
        "review_items" => "Controlla i tuoi prodotti",
        "cart_empty" => "Il carrello e vuoto.",
        "total_amount" => "Importo totale",
        "demo_checkout_note" => "Cliccando Pagamento accetti che questo e un demo.",
        "stock_issues" => "Problemi di disponibilita",
        "stock_changed" => "La disponibilita e cambiata",
        "stock_too_low" => "Disponibilita insufficiente",
        "only_available" => "Solo",
        "available" => "Disponibili",
        "requested" => "Richiesti",
        "in_cart" => "nel carrello",
        "back_to_cart" => "Torna al carrello",
        "secure_checkpoint" => "Controllo sicuro",
        "shipping_details" => "Dettagli spedizione",
        "payment_details" => "Dettagli pagamento",
        "first_name" => "Nome",
        "last_name" => "Cognome",
        "address" => "Indirizzo",
        "city" => "Citta",
        "zip_code" => "CAP",
        "country" => "Paese",
        "card_number" => "Numero carta",
        "expiry" => "Scadenza",
        "pay" => "Paga",
        "demo_payment" => "Pagamento demo - nessuna verifica carta",
        "order_summary" => "Riepilogo ordine",
        "currency" => "Valuta",
        "promo_code" => "Inserisci codice promo",
        "apply" => "Applica",
        "discount" => "Sconto",
        "order_success" => "Ordine effettuato con successo",
        "delivery" => "Consegna in 2-3 giorni lavorativi",
        "view_invoice" => "Vedi fattura",
        "invoice" => "Fattura",
        "invoice_details" => "Dettagli fattura",
        "print_invoice" => "Stampa fattura",
        "thank_purchase" => "Grazie per il tuo acquisto",
        "customer" => "Cliente",
        "date" => "Data",
        "view_details" => "Vedi dettagli",
        "order_history" => "La cronologia dei tuoi ordini TechTrade",
        "no_orders" => "Non hai ancora ordini.",
        "order" => "Ordine",
        "item_total" => "Totale articolo",
        "order_id" => "ID ordine",
        "order_date" => "Data ordine",
        "catalog" => "Catalogo",
        "filter_by" => "Filtra per",
        "go" => "Vai",
        "view_all" => "Vedi tutto",
        "no_products" => "Nessun prodotto trovato in questa categoria.",
        "my_wishlist" => "I miei preferiti",
        "wishlist_subtitle" => "La tua collezione salvata",
        "wishlist_empty" => "La lista preferiti e vuota.",
        "explore_products" => "Esplora prodotti",
        "login_to_buy" => "Accedi per acquistare",
        "remove_wishlist" => "Rimuovi dai preferiti",
        "add_wishlist" => "Aggiungi ai preferiti",
        "footer_text" => "Creato per appassionati di tecnologia premium.",
    ],
];

function t(string $key): string
{
    global $translations, $lang;

    return $translations[$lang][$key] ?? $key;
}

function language_url(string $selectedLang): string
{
    $params = $_GET;
    $params["lang"] = $selectedLang;
    $query = http_build_query($params);

    return strtok($_SERVER["REQUEST_URI"], "?") . ($query ? "?" . $query : "");
}
